name: Package up and publish

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIG: "Release"
      OUT_FOLDER: "./build.out/"

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version with GitVersion (MSBuild in Proj will do this)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: ./GitVersion.yml

      - name: Display GitVersion SemVer
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      # ------------------------
      # build and package uSync packages
      # ------------------------

      - name: Add package source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/michaelchart/index.json"

      - name: Restore
        run: dotnet restore ./src/Etch.uSyncMigrations.BlockListSettings.sln

      - name: Build Etch.uSyncMigrations.BlockListSettings
        run: dotnet pack ./src/Etch.uSyncMigrations.BlockListSettings/Etch.uSyncMigrations.BlockListSettings.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

      - name: Upload nuget file as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Nuget Build Output
          path: ${{env.OUT_FOLDER}}

      - name: Push to Nuget
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          dotnet nuget push ${{env.OUT_FOLDER}}Etch.uSyncMigrations.BlockListSettings.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }}
